baseURL = 'https://acpedia.pages.dev/'
theme = "hugo-bearblog"
title = "ACPEDIA®"

[languages]
  [languages.id]
    label = "Bahasa Indonesia"
    locale = "id-ID"
    title = "ACPEDIA®"

[params]
  post_navigation = true
  madeWith = false
  copyright = "© 2026 ACPEDIA®"
  
  
  
  
  
  description = "Ensiklopedia dan panduan pendingin ruangan (AC) dari A sampai Z untuk pemula."
  author = "ACPEDIA®"
  theme = "toggle"

[menu]
  [[menu.main]]
    name = "Mulai dari Sini"
    url = "/mulai/"
    weight = 1

  [[menu.main]]
    name = "Semua Tulisan"
    url = "/blog/"
    weight = 2

  

  [[menu.main]]
    name = "Glosarium"
    url = "/glosarium/"
    weight = 4

  [[menu.main]]
    name = "Tentang"
    url = "/tentang/"
    weight = 5
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
disableTaxonomies = ["taxonomy", "term"]